### ISSUE TITLE
ImportError: No module named pw_material

### ISSUE THREAD

**Issue by uid89626** [aitatanit/gmes#1]
>>> import gmes
No module named psyco. Execution speed might be slow.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/gmes/__init__.py", line 51, in <module>
    from fdtd import *
  File "/usr/local/lib/python2.7/dist-packages/gmes/fdtd.py", line 25, in <module>
    from file_io import Probe
  File "/usr/local/lib/python2.7/dist-packages/gmes/file_io.py", line 23, in <module>
    from pw_material import MaterialElectricReal, MaterialElectricCmplx
ImportError: No module named pw_material

**Comment by yu-ting-py** [comment]
After I use cmd to install your package, it apprears
running install
running build
running build_py
creating build
creating build\lib.win-amd64-3.6
creating build\lib.win-amd64-3.6\gmes
copying gmes\fdtd.py -> build\lib.win-amd64-3.6\gmes
copying gmes\file_io.py -> build\lib.win-amd64-3.6\gmes
copying gmes\geometry.py -> build\lib.win-amd64-3.6\gmes
copying gmes\pw_source.py -> build\lib.win-amd64-3.6\gmes
copying gmes\show.py -> build\lib.win-amd64-3.6\gmes
copying gmes\source.py -> build\lib.win-amd64-3.6\gmes
copying gmes\__init__.py -> build\lib.win-amd64-3.6\gmes
running build_ext
building 'gmes._pw_material' extension
swigging src\pw_material.i to src\pw_material_wrap.cpp
swig.exe -python -c++ -outdir gmes -o src\pw_material_wrap.cpp src\pw_material.i
error: command 'swig.exe' failed: No such file or directory

-----------------------------------------------------------------------------------
Could anyone tell me how to fix it?

Thanks in advance.
